"""Hardware advisor + documentation generator — plan §21.23 + §21.24.

Two closeout features that compound the existing engine surface:

- :func:`hardware_advice` — given a Stack, recommend a hardware class
  + estimated cost-to-train / cost-to-infer.
- :func:`generate_docs` — given a Stack, emit a paper-appendix-quality
  markdown describing the architecture.

Both run from pure Python on top of the native `graphnet` bindings
(`stack.op_tags()`, `stack.dim()`, `stack.len()`).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class HardwareRecommendation:
    """Recommended hardware class for a given architecture."""

    cpu_class: str
    """e.g. "modern laptop", "8-core workstation"."""
    ram_gb: int
    """Recommended host RAM in GiB."""
    gpu_class: str
    """e.g. "none", "consumer GPU (RTX 4070)", "datacenter (A100)"."""
    vram_gb: int
    """Recommended VRAM in GiB. 0 if no GPU needed."""
    estimated_inference_wall_ms: float
    """Estimated wall-time per forward pass on the recommended hardware."""
    estimated_kwh_per_million_inferences: float
    """Energy estimate at the recommended hardware."""
    notes: list[str]
    """Free-form advice."""


def hardware_advice(stack: Any) -> HardwareRecommendation:
    """Recommend hardware class for a given Stack architecture.

    Heuristic-based; not a benchmark. Treats Identity/Dense as O(D),
    HrrBind as O(D log D), and Stack overhead as O(N * D) for N ops.

    Requires the native graphnet extension.
    """
    import graphnet

    if graphnet.Stack is None:
        raise RuntimeError("native graphnet not installed")

    d = stack.dim()
    n = len(stack)
    tags = stack.op_tags()
    has_fft = "hrr_bind" in tags

    # Per-forward FLOP estimate (very rough).
    base_flops = n * d  # one multiply-add per dim per op
    fft_extra = (
        sum(d * max(1, int(d.bit_length())) for tag in tags if tag == "hrr_bind") // 8
    )
    total_flops = base_flops + fft_extra

    # Wall-time estimate: assume 10 GFLOPS sustained on a modern CPU.
    cpu_flops_per_sec = 10e9
    wall_ms = (total_flops / cpu_flops_per_sec) * 1000.0

    notes: list[str] = []
    cpu_class = "modern laptop"
    ram_gb = 4
    gpu_class = "none"
    vram_gb = 0

    if d >= 10_000 and n >= 5:
        cpu_class = "8-core workstation or better"
        ram_gb = 8
    if has_fft and d >= 10_000:
        notes.append("HrrBind at D≥10_000 is FFT-heavy; consider GPU for ≥10k forwards/s.")
        if n >= 3:
            gpu_class = "consumer GPU (RTX 4070 or similar)"
            vram_gb = 8

    # Energy: 65 W laptop CPU baseline; 300 W consumer GPU when present.
    watts = 65.0 if gpu_class == "none" else 300.0
    secs_per_forward = wall_ms / 1000.0
    joules_per_million = watts * secs_per_forward * 1_000_000.0
    kwh_per_million = joules_per_million / 3_600_000.0

    if total_flops > 1e9:
        notes.append(f"Per-forward FLOPs ≈ {total_flops:.2e}; non-trivial workload.")
    if n >= 8:
        notes.append("Consider splitting into a Stack-of-Stacks for parallel substructure scaling.")

    return HardwareRecommendation(
        cpu_class=cpu_class,
        ram_gb=ram_gb,
        gpu_class=gpu_class,
        vram_gb=vram_gb,
        estimated_inference_wall_ms=wall_ms,
        estimated_kwh_per_million_inferences=kwh_per_million,
        notes=notes,
    )


def generate_docs(stack: Any, *, title: str | None = None) -> str:
    """Generate a markdown documentation report for a Stack.

    The output is suitable for a paper appendix or internal review. It
    documents shape + per-op type + estimated cost + advisor recommendation.

    Requires the native graphnet extension.
    """
    import graphnet

    if graphnet.Stack is None:
        raise RuntimeError("native graphnet not installed")

    d = stack.dim()
    n = len(stack)
    tags = stack.op_tags()
    advice = hardware_advice(stack)

    title = title or f"Stack (dim={d}, ops={n})"
    op_table = "\n".join(f"| {idx} | `{tag}` |" for idx, tag in enumerate(tags))
    notes_md = "\n".join(f"- {note}" for note in advice.notes) or "- (no specific notes)"

    return f"""# {title}

## Shape

- **Dimensionality**: {d}
- **Operations**: {n}
- **Family**: stack (heterogeneous bundle on shared HDC vector)

## Operations

| Index | Tag |
|-------|-----|
{op_table}

## Hardware recommendation

- **CPU**: {advice.cpu_class}
- **RAM**: {advice.ram_gb} GiB
- **GPU**: {advice.gpu_class}
- **VRAM**: {advice.vram_gb} GiB

## Performance estimate

- Estimated wall-time per forward pass: **{advice.estimated_inference_wall_ms:.3f} ms**
- Estimated energy per million inferences: **{advice.estimated_kwh_per_million_inferences:.3f} kWh**

## Notes

{notes_md}

---

Generated by `graphnet.advisor.generate_docs` (Phase 11 wave 2). For
the canonical architecture spec (machine-readable, content-hashed),
see [`stack_to_yaml`](https://github.com/thepictishbeast/PlausiDen-GraphNet).
"""
